/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux turing 4.15.15-1-ARCH x86_64"
#define LGL_COMPILED "Sun Apr 15 15:39:08 CEST 2018"
#define LGL_RELEASED "Thu Jul  7 10:21:35 CEST 2016"
#define LGL_VERSION "bbc"
#define LGL_ID "923038088b727dcc8bd03aa8dfb5013bd03bf8c4"
